<?php


namespace App\Services\Concrete\Letter;


use App\Services\AbstractResourceService;
use Illuminate\Database\Eloquent\Model;

class LetterService extends AbstractResourceService
{
    public function store(Model $model): bool
    {
        $model->hr_id = $model->hr_id ??  auth()->id();
        return parent::store($model); // TODO: Change the autogenerated stub
    }

}
